export enum RecordType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
  SOCIALINCOME = 'SOCIALINCOME',
  SOCIALEXPENSE = 'SOCIALEXPENSE',
}

export enum StatusValue {
  INCOME = 1,
  EXPENSE = 2,
  SOCIALINCOME = 3,
  SOCIALEXPENSE = 4,
}
